// SPDX-FileCopyrightText: 2026 Julien Mary <julien@quackkiller.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#include <glib.h>
#include <glib/gstdio.h>
#include <stdio.h>
#include <string.h>

#include "pipewire-export.h"
#include "custom-names.h"
#include "stereo-link.h"

// Get the name for a routing source, considering stereo link.
// If linked, uses pair name + L/R suffix.
// Returns newly allocated string.
static char *get_src_export_name(struct routing_src *src) {
  if (is_src_linked(src)) {
    // Get the left channel of the pair
    struct routing_src *left = is_src_left_channel(src) ? src : src->partner;
    char *pair_name = get_src_pair_display_name(left);

    char *name;
    if (is_src_left_channel(src))
      name = g_strdup_printf("%s L", pair_name);
    else
      name = g_strdup_printf("%s R", pair_name);

    g_free(pair_name);
    return name;
  }

  return g_strdup(src->display_name ? src->display_name : src->name);
}

// Get the name for a routing sink, considering stereo link.
// If linked, uses pair name + L/R suffix.
// Returns newly allocated string.
static char *get_snk_export_name(struct routing_snk *snk) {
  if (is_snk_linked(snk)) {
    // Get the left channel of the pair
    struct routing_snk *left = is_snk_left_channel(snk) ? snk : snk->partner;
    char *pair_name = get_snk_pair_display_name(left);

    char *name;
    if (is_snk_left_channel(snk))
      name = g_strdup_printf("%s L", pair_name);
    else
      name = g_strdup_printf("%s R", pair_name);

    g_free(pair_name);
    return name;
  }

  return g_strdup(snk->display_name ? snk->display_name : snk->elem->name);
}

// Collect display names for HW ports (PC_HW) from routing sources,
// ordered by hw_type (Analogue, SPDIF, ADAT) and port_num.
// These map 1:1 to PipeWire capture channels.
static GArray *collect_hw_src_names(struct alsa_card *card) {
  GArray *names = g_array_new(FALSE, FALSE, sizeof(char *));

  for (int hw = 0; hw < HW_TYPE_COUNT; hw++) {
    for (int i = 0; i < card->routing_srcs->len; i++) {
      struct routing_src *src = &g_array_index(
        card->routing_srcs, struct routing_src, i
      );
      if (src->port_category == PC_HW && src->hw_type == hw) {
        char *name = get_src_export_name(src);
        g_array_append_val(names, name);
      }
    }
  }

  return names;
}

// Collect display names for HW ports (PC_HW) from routing sinks,
// ordered by hw_type (Analogue, SPDIF, ADAT) and port_num.
// These map 1:1 to PipeWire playback channels.
static GArray *collect_hw_snk_names(struct alsa_card *card) {
  GArray *names = g_array_new(FALSE, FALSE, sizeof(char *));

  for (int hw = 0; hw < HW_TYPE_COUNT; hw++) {
    for (int i = 0; i < card->routing_snks->len; i++) {
      struct routing_snk *snk = &g_array_index(
        card->routing_snks, struct routing_snk, i
      );
      if (snk->elem->port_category == PC_HW && snk->elem->hw_type == hw) {
        char *name = get_snk_export_name(snk);
        g_array_append_val(names, name);
      }
    }
  }

  return names;
}

// Format names array as a JSON-like WirePlumber array string with
// numeric prefix for Ardour sort order.
// prefix: "In" or "Out"
static char *format_channel_names(GArray *names, const char *prefix) {
  GString *s = g_string_new("[");

  for (guint i = 0; i < names->len; i++) {
    char *name = g_array_index(names, char *, i);

    if (i > 0)
      g_string_append(s, ", ");

    g_string_append_printf(s, "\"%s %02d %s\"", prefix, i + 1, name);
  }

  g_string_append(s, "]");

  return g_string_free(s, FALSE);
}

// Free names array
static void free_names(GArray *names) {
  for (guint i = 0; i < names->len; i++)
    g_free(g_array_index(names, char *, i));
  g_array_free(names, TRUE);
}

// Build the WirePlumber config file content
static char *build_config(struct alsa_card *card) {
  GArray *in_names = collect_hw_src_names(card);
  GArray *out_names = collect_hw_snk_names(card);

  char *in_str = format_channel_names(in_names, "In");
  char *out_str = format_channel_names(out_names, "Out");

  char *config = g_strdup_printf(
    "# Generated by alsa-scarlett-gui for device serial %s\n"
    "# Do not edit manually — regenerate with \"Export Names to PipeWire\"\n"
    "\n"
    "monitor.alsa.rules = [\n"
    "  {\n"
    "    matches = [\n"
    "      { node.name = \"~alsa_input.*%s.*source\" }\n"
    "    ]\n"
    "    actions = {\n"
    "      update-props = {\n"
    "        node.channel-names = %s\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "  {\n"
    "    matches = [\n"
    "      { node.name = \"~alsa_output.*%s.*sink\" }\n"
    "    ]\n"
    "    actions = {\n"
    "      update-props = {\n"
    "        node.channel-names = %s\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "]\n",
    card->serial,
    card->serial, in_str,
    card->serial, out_str
  );

  g_free(in_str);
  g_free(out_str);
  free_names(in_names);
  free_names(out_names);

  return config;
}

// Check if WirePlumber is running
static gboolean is_wireplumber_running(void) {
  int status;
  gboolean ok = g_spawn_command_line_sync(
    "systemctl --user is-active wireplumber",
    NULL, NULL, &status, NULL
  );
  return ok && status == 0;
}

// Restart WirePlumber
static gboolean restart_wireplumber(void) {
  int status;
  gboolean ok = g_spawn_command_line_sync(
    "systemctl --user restart wireplumber",
    NULL, NULL, &status, NULL
  );
  return ok && status == 0;
}

int pipewire_export_names(struct alsa_card *card) {
  if (!card || !card->serial || !*card->serial)
    return -1;

  if (!card->routing_srcs || !card->routing_snks)
    return -1;

  // Build config directory path
  const char *config_home = g_get_user_config_dir();
  char *dir = g_build_filename(
    config_home, "wireplumber", "wireplumber.conf.d", NULL
  );

  // Create directory if needed
  if (g_mkdir_with_parents(dir, 0755) < 0) {
    g_warning("Failed to create directory: %s", dir);
    g_free(dir);
    return -1;
  }

  // Build file path
  char *filename = g_strdup_printf("90-focusrite-%s.conf", card->serial);
  char *path = g_build_filename(dir, filename, NULL);

  g_free(dir);
  g_free(filename);

  // Generate config content
  char *config = build_config(card);

  // Write file
  GError *error = NULL;
  if (!g_file_set_contents(path, config, -1, &error)) {
    g_warning("Failed to write %s: %s", path, error->message);
    g_error_free(error);
    g_free(config);
    g_free(path);
    return -1;
  }

  g_free(config);
  g_free(path);

  // Restart WirePlumber if running
  if (is_wireplumber_running()) {
    if (!restart_wireplumber()) {
      g_warning("Failed to restart WirePlumber");
      return -1;
    }
  }

  return 0;
}
